### ISSUE TITLE
undefined symbol: gettid with rust code

### ISSUE THREAD

**Issue by 0xtyls** [intel/iodlr#82]
Hi,

I try to use liblppreload.so with a rust program and get this error: 

symbol lookup error: /usr/lib64/liblppreload.so: undefined symbol: gettid

What did I miss?

**Comment by gsauthof** [comment]
This is due to a forward declaration of `gettid()`

https://github.com/intel/iodlr/blob/ea65db1016bac729f3b3442d072dce3242ee50c8/large_page-c/lp_preload.c#L10C1-L10C20

and your system's libc not providing `gettid()`. See also:

> The gettid() system call first appeared on Linux in kernel 2.4.11.  Li‐
       brary support was added in glibc 2.30.  (Earlier glibc versions did not
       provide  a  wrapper  for  this  system  call,  necessitating the use of
       [syscall(2)](https://manpath.be/f37/2/syscall).)

([gettid(2)](https://manpath.be/f37/2/gettid#L28))

To work around it you can simply comment-out its sole usage:

https://github.com/intel/iodlr/blob/ea65db1016bac729f3b3442d072dce3242ee50c8/large_page-c/lp_preload.c#L42
